API/urls.py
from django.contrib import admin
from django.urls import path, include
from home_app_new import views
from basic_app_new import views
from FoodIndex_new import views


admin.site.site_header = "Food Index Admin Page"
admin.site.site_title = "Food index"
admin.site.index_title = "Admin Page"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FoodIndex_new.urls')),
    path('home/', include('home_app_new.urls')),
    path('', include('basic_app_new.urls'))
]

FoodIndex_new/urls.py
from django.contrib import admin
from django.urls import path, include
from FoodIndex_new import views
from FoodIndex_new.views import *
from django.conf.urls.static import static
from django.conf import settings
from home_app_new import views as hviews
from basic_app_new import views as bviews
app_name='FoodIndex_new'
urlpatterns = [
    path('upload_csv', views.upload_csv, name='upload_csv'),    
    path('filetodb', views.file_to_db, name='filetodb'),
    path('addfood', views.addfood, name='addfood'),
    path('getdata', views.getdata, name='getdata'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('admin_page', views.admin_page, name='admin_page'),
    path('alreadyuser', views.abc, name='alreadyuser'),
    path('base_table', views.base_table, name='base_table'),
    path('upload_csv_', views.xyz, name='upload_csv_'),
    path('user_signup', views.user_signup, name='user_signup'),
    path('user_signup_', views.createnewuser, name='user_signup'),
    path('home', hviews.home, name='home'),
    path('north', bviews.north, name='north'),
    path('table', hviews.table, name='table'),
    path('purchase', hviews.purchase, name='purchase'),
    path('', views.user_login, name='user_login'),
    path('profile_page',hviews.profile_page,name='profile_page'),
    path('search',bviews.search,name='search'),
    path('delete/<str:food_id>',views.delete_food,name="delete"),
    #path('chart',hviews.chart,name='chart'),
	#path('calchartthree',hviews.calchartthree,name='calchartthree'),
    path('update/<str:food_id>', views.update_food, name='update'),
    path('delete_table', views.delete_table, name='delete_table'),
    path('home/userfoodlogchart', hviews.userfoodlogchart, name='userfoodlogchart'),
    path('nut/', hviews.HomeView.as_view(),name='nut'),
    path('api', hviews.ChartData.as_view(),name='api'),
    path('chartof',hviews.chartof,name='chartof'),
    path('bb/',hviews.bb,name='bb'),
    path('amazon/',hviews.amazon,name='amazon'),
    path('grofers/',hviews.grofers,name='grofers'),
    path('south/',hviews.south,name='south'),
    path('chinese/',hviews.chinese,name='chinese'),
	path('continental/',hviews.continental,name='continental'),
	path('sweet/',hviews.sweet,name='sweet'),
    path('others/',hviews.others,name='others'),
    path('cuisine_consumed/',hviews.cuisine_consumed,name='cuisine_consumed'),
    path('purchase_table', views.purchase_table, name='purchase_table'),
    path('admin_login_purchase', views.admin_login_purchase, name='admin_login_purchase'),
    path('consumption_table', views.consumption_table, name='consumption_table'),
    path('admin_login_consumption', views.admin_login_consumption, name='admin_login_consumption'),
    path('delete_purchase/<str:id>',views.delete_purchase_food,name="delete"),
    path('update_purchase/<str:id>', views.update_purchase_food, name='update'),
    path('delete_table', views.delete_table, name='delete_table'),
    path('add_purchase_food', views.addpurchasefood, name='add_purchase_food'),
	path('foodtopanadmin',hviews.foodtopanadmin,name='foodtopanadmin'),
	path('csvtopanadmin',hviews.csvtopanadmin,name='csvtopanadmin'),
	path('csvtopanadmin_',hviews.csvtopanadminloader,name='csvtopanadmin_'),




    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL)


home_app_new/urls.py
from django.urls import path,include
from home_app_new import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
app_name='home_app_new'


urlpatterns=[
	path('home/',views.home,name='home'),
	#path('renderhome/',views.renderhome, name='renderhome'),
	path('details/<str:f_name>/', views.details, name='details'),
    path('add_item1/', views.add_item1, name='add_item1'),
	path('delete/<str:f_name>/', views.delete, name='delete'),
	path('delete_purchase/<str:f_id>/', views.delete_purchase, name='delete_purchase'),
	path('delete_purchase2/<str:f_id>/', views.delete_purchase2, name='delete_purchase2'),
	path('table/', views.table, name='table'),
	path('purchase/', views.purchase, name='purchase'),
	path('confirm_purchase/', views.confirm_purchase, name='confirm_purchase'),
	path('other_purchase/', views.other_purchase, name='other_purchase'),
	path('confirm_purchase2/', views.confirm_purchase2, name='confirm_purchase2'),
	path('save_table/', views.save_table, name='save_table'),
	path('save_purchase/', views.save_purchase, name='save_purchase'),
	path('deletetemp/',views.deletetemp, name='deletetemp'),
	
	path('foodtopan',views.foodtopan,name='foodtopan'),
    path('profile_page/',views.profile_page,name='profile_page'),
	path('nut/', views.HomeView.as_view(),name='nut'),
    path('api', views.ChartData.as_view(),name='api'),
    path('chartof',views.chartof,name='chartof'),
	path('purchase_status',views.purchase_status,name='purchase_status'),
	path('consumer_history',views.consumer_history,name='consumed_history'),
	path('purchasechart', views.purchasechart, name='purchasechart'),
	path('otherdayanalysis', views.otherdayanalysis, name='otherdayanalysis'),
	path('consumeComparison', views.consumeComparison, name='consumeComparison'),
	path('purchaseComparison', views.purchaseComparison, name='purchaseComparison'),
	path('cuisine_cards/',views.cuisine_cards,name='cuisine_cards'),
	path('south/',views.south,name='south'),
	path('chinese/',views.chinese,name='chinese'),
	path('continental/',views.continental,name='continental'),
	path('sweet/',views.sweet,name='sweet'),
	path('confirm_consumption/',views.confirm_consumption,name='confirm_consumption'),
	path('confirm_consumption2/',views.confirm_consumption2,name='confirm_consumption2'),
	path('cuisine_consumed/',views.cuisine_consumed,name='cuisine_consumed'),
	path('delete_cuisine/<str:c_id>/',views.delete_cuisine,name='delete_cuisine'),
	path('delete_cuisine2/<str:c_id>/',views.delete_cuisine2,name='delete_cuisine2'),
	path('confirm_file1/',views.confirm_file1,name='confirm_file1'),
	path('confirm_file2/',views.confirm_file2,name='confirm_file2'),
	path('confirm_file3/',views.confirm_file3,name='confirm_file3'),
	path('confirm_file4/',views.confirm_file4,name='confirm_file4'),
	path('save_cuisine/',views.save_cuisine,name='save_cuisine'),
	path('amazon/',views.amazon,name='amazon'),
	path('grofers/',views.grofers,name='grofers'),
	path('bb/',views.bb,name='bb'),
	path('others/',views.others,name='others'),
	path('amazon_search/',views.amazon_search,name='amazon_search'),
	path('bb_search/',views.bb_search,name='bb_search'),
	path('other_search/',views.other_search,name='other_search'),
	path('groffers_search/',views.groffers_search,name='groffers_search'),
	path('south_search/',views.south_search,name='south_search'),
	path('continental_search/',views.continental_search,name='continental_search'),
	path('sweet_search/',views.sweet_search,name='sweet_search'),
	path('chinese_search/',views.chinese_search,name='chinese_search'),
	path('foodtopanadmin',views.foodtopanadmin,name='foodtopanadmin'),
	path('consumption_cuisine_status',views.consumption_cuisine_status,name='consumption_cuisine_status'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/consumption_table_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>consumption_table</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Food Diary</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> &nbsp;&nbsp
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'FoodIndex_new:base_table'%}">Food Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'FoodIndex_new:purchase_table'%}">Purchase Table</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'FoodIndex_new:consumption_table'%}">Pancare Food Table</a>
                </li>
                </ul>
                </div>
            <a href="{% url 'home_app_new:deletetemp' %}"><button type="submit" style="height: 1%;" class="btn btn-danger ">Logout</button></a>
        </div>
        

    </nav>
    <div id="FoodMaster">
        <p id="title">Pancare Table</p>
        <p class="text-center">
            <span><a href="foodtopanadmin"><button class="btn btn-info" type="submit" formaction="foodtopanadmin">Add New
                        Food</button></a>
            </span>
            <span><a href="csvtopanadmin"><button class="btn btn-primary" type="submit" formaction="csvtopanadmin">Batch Upload To Pancare</button></a>
            </span>
            
        </p>
    </div>
    
        <style>
            #descrp{
             width: 20rem;
            }
            .navbar {
                box-shadow: 0 4px 8px 0 rgba(89, 67, 216, 0.482);
            }
            
            .container-fluid {
                background-color: rgb(255, 255, 255);
                margin-top: 0 !important;
                padding-top: 0.7rem;
                width: fit-content !important;
            }
            
            body {
                background-size: cover;
                background-color: rgb(250, 250, 250);
                padding: 0 !important;
            }
            
            #FoodMaster {
                text-align: center;
                font-size: 30px;
                background-color: rgb(255, 255, 255);
                margin-bottom: 0;
                width: fit-content;
                margin-right: auto;
                margin-left: auto;
                padding: 1rem;
            }
            
            #title {
                margin: 1rem auto 1.5rem auto;
                color: rgb(69, 5, 117);
                font-family: Georgia, 'Times New Roman', Times, serif;
                font-weight: 500;
                font-size: 40px;
                background: rgb(247, 246, 248);
                width: fit-content;
                padding: .3rem 1.5rem;
                border: 2px solid black;
                border-radius: 12px;
            }
            
            #table {
                border-style: solid !important;
                border-color: midnightblue !important;
                border-width: 2px !important;
                border-radius: 5px;
                width: 100rem;
                
            }
            
            th {
                text-align: center;
                text-transform: uppercase;
            }
            
            td {
                text-align: center;
            }
        </style>


  <table id="table" border="5">
    <thead>
      <tr>
        <th>Mfg Code</th>
        <th>FoodName</th>
        <th width="20">Description</th>
        <th>serving_style</th>
        <th>Carbohydrate</th>
        <th>Protein</th>
        <th>Fat</th>
        <th>Fiber</th>
        <th>Sugar</th>
        <th>Calories</th>
        <th>Image</th>
        <!--<th>Edit</th>
        <th>Delete </th>-->
      </tr>
    </thead>
    <tbody>
    <!-- jinja2 Technique -->
    {% if dataframe %}  
    {% for i in dataframe %}
      <tr>
        <td>{{i.mfg_code}}</td>
        <td>{{i.food_name}}</td>
        <td id="descrp">{{i.description}}</td>
        <td>{{i.ss_code}}</td>
        <td>{{i.carbs}}</td>
        <td>{{i.protein}}</td>
        <td>{{i.fat}}</td>
        <td>{{i.fiber}}</td>
        <td>{{i.sugar}}</td>
        <td>{{i.calorie}}</td>
        <td><img src="{{ i.image_path}}" height="100px" width="100px"></img></td>
      <!--  <td><button type="button" class="btn btn-primary">Edit</button></td>
        <td><button type="button" class="btn btn-danger">Delete</button></td>-->
      </tr>
    {% endfor %}
    {% endif %}
    </tbody>
  </table>
</div>
  
</body>
</html>

templates/details.html
 {%extends 'base.html'%} {% block body_block%} {% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Food Details</title>
</head>

<body>
    {% if info %}

    <br><br>
    <div class="d-flex justify-content-center">
        <div class="m-4">
            <div class="d-flex justify-content-center">
                <p>
                    <h2>{{info.food_name}}</h2>
                </p>
            </div><br>
            <div class="card" style="width: 23rem;">
                <img class="card-img-top" src="{{image_link}}" alt="Food" onerror=this.src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" height="220" width="220">
                <div class="card-body">
                    <h5 class="card-title">Nutritional Facts of {{info.food_name}}</h5>

                </div>
                <div class="float-right">
                    <div class="d-flex justify-content-center">
                        <ul class="list-group list-group-flush">

                            <li class="list-group-item">Calories: {{info.calorie}}</li>
                            <li class="list-group-item">Protien : {{info.protein}}g</li>
                            <li class="list-group-item">Fat : {{info.fat}}g</li>
                            <li class="list-group-item">Carbohydrates : {{info.carbs}}g</li>
                            <li class="list-group-item">Sodium : {{info.sodium}}g</li>
                            <li class="list-group-item">Sugar : {{info.sugar}}g</li>
                            <li class="list-group-item">Alchohol : {{info.alchohol}}g</li>
                            <li class="list-group-item">Fiber content : {{info.fiber}}g</li>
                            <li class="list-group-item">Calorie Saturated Fats : {{info.calorie_saturated_fat}}g</li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% endif %}
</body>

</html>
{% endblock %}

templates/error.html
<div>
<br><br>

<h1>OOPS!! Wrong file format!! Please check the file format : </h1>


          <div class="modal-body">
              <p>The CSV file you upload should be of the following format & the order should be strictly maintained:</p>
              <br>
            <img src="https://i.ibb.co/XxbNDwt/Screenshot-1107.png" alt="" width="750">
            <br><br>
            <ul class="list-group">
                <li class="list-group-item">Protiens,fats,carbohydrates should be specified in grams</li>
                <li class="list-group-item">Quantity should be an integer</li>
                <li class="list-group-item">Meal type can be any of the follwong: Breakfast/Lunch/Dinner/Snacks</li>
              </ul>
          </div>
      
        </div>

templates/error3.html
<div>
    <br><br>
    
    <h1>OOPS!! Wrong file format!! Please check the file format : </h1>
    
    
    <br><br>
    <ul class="list-group">
        <li class="list-group-item">Columns should be in the order: food name,
            quantity,
            serving style,
            carbs,
            protein,
            fat,
            fiber,
            sugar,
            sodium,
            alchohol,
            calorie,
            calorie saturated fats,
        mfg code</li>
        <li class="list-group-item">Protiens,fats,carbohydrates,etc should be specified in grams</li>
        <li class="list-group-item">Quantity should be an integer</li>
        <li class="list-group-item">Serving style can be any of the following: Solid/Liquid</li>
      </ul>

    </div>

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}

        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            {{ message }}

    </div>
    {% endfor %}
</ul>
{% endif %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>Admin Sign Up</title>
</head>

<body>
    <style>
        .container-fluid {
            width: 50vw;
            height: 100vh;
            background-color: rgb(255, 255, 255);
            margin-top: 0 !important;
            padding-top: 0.7rem;
        }

        body {
            background-size: cover;
            background-color: rgb(255, 255, 255);
            padding: 0 !important;
        }

        #title {
            margin: 1rem auto 1.5rem auto;
            color: rgb(69, 5, 117);
            font-family: Georgia, 'Times New Roman', Times, serif;
            font-weight: 500;
            background: rgb(247, 246, 248);
            width: fit-content;
            padding: .3rem 1.5rem;
            border: 2px solid black;
            border-radius: 12px;
        }

        .btnx {
            background-color: white;
            color: black;
            border: 2px solid #001a61;
        }

        .btnx:hover {
            background-color: #7bf1e2;
            color: white;
        }
    </style>
    <div class="container-fluid">
        <h1 id="title">Admin Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            {% include 'messages.html' %}
            <input name="admin_nm" type="text" placeholder="Admin Name" required autofocus>
            <input name="admin_id" type="text" placeholder="Admin I.D." required autofocus>
            <input name="phone" type="tel" placeholder="Phone Number" required autofocus>
            <input name="email" type="email" placeholder="Email ID" required autofocus>
            <input name="password" type="password" placeholder="Enter Password" required autofocus>
            <input name="repass" type="password" placeholder="Re-Enter Password" required autofocus>
            <br>
            <br>
            <button class="btn btn-outline-success" type="submit" formaction="admin_login">Add Admin</button>
            <button class="btn btnx" type="submit" formaction="login"><a href="/">Go To User
                    login</a></button>
            <br>
            <br>
            <a href="alreadyuser">Already A User?</a>
        </form>
        <br>

    </div>

</body>

</html>

templates/update_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Update Food</title>
</head>

<body>
    {% block content %}
    <center>
        <h1 class="display-3" style="background-color:#000000;color:#FFFF99;">Update Food</h1>
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <table class='w-50 table table-light' style="border-radius:10px;background-color:#FFFF99;">
                {% for i in update_form %}
                <tr>
                    <th>{{i.label}}</th>
                    <td>{{ i }}</td>
                </tr>
                {% endfor %}
            </table>
            <button type="submit" class="btn btn-lg btn-warning">Submit</button>
        </form>
    </center>
    {% endblock %}

</body>

</html>

templates/user_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>User Login</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            background-color:white;
          
        }

        .container-fluid {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .card {
            margin-bottom: 20px;
            border: none
        }

        .text-muted {
            color: cornflowerblue;
        }

        .box {
            margin-left: auto;
            margin-right: auto;
            display: block;
            width: 500px;
            padding: 40px;
            background-color: ghostwhite;
            text-align: center;
            transition: 0.25s;
            border-radius: 25px;
        }

        .box input[type="text"],
        .box input[type="password"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #3498db;
            padding: 10px 10px;
            width: 250px;
            outline: none;
            color: dodgerblue;
            border-radius: 24px;
            transition: 0.25s
        }

        .box h1 {
            color:dodgerblue;
            text-transform: uppercase;
            font-weight: 500
        }

        .box input[type="text"]:focus,
        .box input[type="password"]:focus {
            width: 300px;
            border-color: #2ecc71
        }

        .box input[type="submit"] {
            border: 0;
            background: none;
            display: block;
            margin: 20px auto;
            text-align: center;
            border: 2px solid #2ecc71;
            padding: 14px 40px;
            outline: none;
            color: dodgerblue;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer
        }

        .box input[type="submit"]:hover {
            background: #2ecc71
        }

        .forgot {
            text-decoration: underline
        }

        ul.social-network {
            list-style: none;
            display: inline;
            margin-left: 0 !important;
            padding: 0
        }

        ul.social-network li {
            display: inline;
            margin: 0 5px
        }

        .social-network a.icoFacebook:hover {
            background-color: #3B5998
        }

        .social-network a.icoTwitter:hover {
            background-color: #33ccff
        }

        .social-network a.icoGoogle:hover {
            background-color: #BD3518
        }

        .social-network a.icoFacebook:hover i,
        .social-network a.icoTwitter:hover i,
        .social-network a.icoGoogle:hover i {
            color: #fff
        }

        a.socialIcon:hover,
        .socialHoverClass {
            color: #44BCDD
        }

        .social-circle li a {
            display: inline-block;
            position: relative;
            margin: 0 auto 0 auto;
            border-radius: 50%;
            text-align: center;
            width: 50px;
            height: 50px;
            font-size: 20px
        }

        .social-circle li i {
            margin: 0;
            line-height: 50px;
            text-align: center
        }

        .social-circle li a:hover i,
        .triggeredHover {
            transform: rotate(360deg);
            transition: all 0.2s
        }

        .social-circle i {
            color: #fff;
            transition: all 0.8s;
            transition: all 0.8s
        }
    </style>
</head>

<body>
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <form class="box" method="POST">
                        {% csrf_token %}

                        <h1>Login</h1>
                        <p class="text-muted"> Please enter your UserID and Password!</p>
                        {% include 'messages.html' %}
                        <input type="text" name="userId" placeholder="UserID">
                        <input type="password" name="pwd" placeholder="Password">

                        <p>
                            <span>
                                <input type="submit" name="login" value="Login" formaction="home">
                                </form>
                                <input type="submit" name="login" value="Admin Login" formaction="admin_page">

                            </span>
                            
                        <!--<p class="text-muted"> New User?</p>
                        <span>
                            <input type="submit" name="signup" value="Sign Up" formaction="user_signup">
                        </span>
                        </p>
                        <div class="col-md-12">
                            <ul class="social-network social-circle">
                                <li><a href="#" class="icoFacebook" title="Facebook"><i
                                            class="fab fa-facebook-f"></i></a>
                                </li>
                                <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a>
                                </li>
                                <li><a href="#" class="icoGoogle" title="Google +"><i
                                            class="fab fa-google-plus"></i></a>
                                </li>
                            </ul>
                        </div>-->
                    
                </div>
            </div>
        </div>
    </div>
</body>

</html>